/**
 * Deterministic LOI assembler — a copy-paste-ready Letter of Intent / Sources
 * Sought response in GovCon Giants' PROVEN format.
 *
 * The point (Eric, 2026-06-13): users don't need clever prose — they need the
 * correct FORMAT with placeholders in the right spots. Before AI, the GovCon
 * Giants playbook was: copy the proven LOI template, swap in your name / past
 * performance / reference projects against the solicitation, submit. Formatting
 * is the thing people can't do. So the LOI is rendered DETERMINISTICALLY from a
 * fixed template — not generated by an LLM — guaranteeing exact format fidelity
 * and labeled fill-in slots ([Your past performance here]) wherever data is
 * missing. The user pastes their info over the brackets and hits submit.
 *
 * Template structure is transcribed from a real winning LOI in the vault:
 * "SS - LOI USCG New London Solicitation #70Z0G118SPFA02700 - Tavares LLC.pdf":
 *   letterhead → date → CO block → Subject → salutation → (a)(b)(c)(d) body →
 *   Responsible Office / Contact Person → Sincerely → RELEVANT EXPERIENCE
 *   (labeled Role/Scope/Value/POC/GC/Phone/Timeliness per reference project).
 *
 * (Memory: sources_sought_loi_prefill, proposal_assist_v1)
 */

import type { LoiFields } from './loi-fields';
import type { VaultContext } from './types';

// A bracketed fill-in slot. Centralized so the UI can later highlight every
// "[…]" as an editable field the user must complete.
const ph = (label: string) => `[${label}]`;

function s(v: unknown): string {
  return typeof v === 'string' ? v.trim() : v == null ? '' : String(v);
}

function fmtMoney(v: unknown): string {
  if (v == null || v === '') return '';
  const n = Number(String(v).replace(/[^0-9.]/g, ''));
  if (!Number.isFinite(n) || n <= 0) return s(v);
  return `$${n.toLocaleString('en-US')}`;
}

/** Mr./Ms. + last name from a full name, or a neutral fallback. */
function salutationName(fullName?: string): string {
  const name = s(fullName);
  if (!name) return ph('Contracting Officer name');
  const last = name.split(/\s+/).pop();
  return last || name;
}

interface ReferenceProject {
  name: string;
  location: string;
  role: string;
  scope: string;
  value: string;
  poc: string;
  gc: string;
  phone: string;
  timeliness: string;
}

/** Build the labeled RELEVANT EXPERIENCE block from vault past performance.
 *  Exported so Volume II (Past Performance) reuses the exact same format. */
export function relevantExperienceBlock(vault: VaultContext | null | undefined): string {
  const rows = (vault?.past_performance || []).filter((p) => {
    const t = s((p as Record<string, unknown>).contract_title);
    // skip obvious empty/stub rows
    return t && !/^\[.*\]$/.test(t);
  });

  const projects: ReferenceProject[] = rows.length
    ? rows.slice(0, 5).map((p) => {
        const r = p as Record<string, unknown>;
        return {
          name: s(r.contract_title) || ph('Reference project name'),
          location: s(r.office) || ph('Location'),
          role: s(r.role) || ph('Prime / Subcontractor'),
          scope: s(r.scope_description) || ph('Scope of work'),
          value: fmtMoney(r.contract_value) || ph('Contract value'),
          poc: s(r.reference_name) || ph('Reference point of contact'),
          gc: s(r.sub_agency) || s(r.agency) || ph('Prime / General Contractor'),
          phone: s(r.reference_phone) || ph('Reference phone'),
          timeliness: 'Completed On Time',
        };
      })
    : // No vault past performance → emit THREE labeled blank slots the user fills.
      [1, 2, 3].map(() => ({
        name: ph('Reference project name'),
        location: ph('Location'),
        role: ph('Prime / Subcontractor'),
        scope: ph('Scope of work'),
        value: ph('Contract value'),
        poc: ph('Reference point of contact'),
        gc: ph('Prime / General Contractor'),
        phone: ph('Reference phone'),
        timeliness: ph('Completed On Time'),
      }));

  const blocks = projects.map((p) =>
    [
      p.name,
      p.location,
      `Role:                        ${p.role}`,
      `Scope of Work:               ${p.scope}`,
      `Contract Value:              ${p.value}`,
      `Point of Contact:            ${p.poc}`,
      `General Contractor:          ${p.gc}`,
      `Telephone Number:            ${p.phone}`,
      `Timeliness of Performance:   ${p.timeliness}`,
    ].join('\n'),
  );

  return `RELEVANT EXPERIENCE\n\n${blocks.join('\n\n')}`;
}

export interface LoiTemplateInput {
  fields: LoiFields | null;          // extracted from the notice
  vault: VaultContext | null;        // bidder identity + past performance
}

/**
 * Render the full LOI letter in the proven format. Every value that isn't known
 * becomes a clearly-labeled [placeholder] so the user knows exactly what to
 * paste where. The OUTPUT IS THE TEMPLATE — no LLM, no invention.
 */
export function assembleLoiTemplate({ fields, vault }: LoiTemplateInput): string {
  const f = fields || {};
  const id = (vault?.identity || {}) as Record<string, unknown>;

  // --- Letterhead (bidder identity) ---
  const company = s(id.legal_name) || ph('Your company name');
  const duns = s(id.duns) || ph('DUNS');
  const cage = s(id.cage_code) || ph('CAGE');
  const addr = s(id.office_address) || ph('Your company address');
  const phone = s(id.contact_phone) || ph('Office phone');

  // --- CO / agency block (from the notice) ---
  const coName = s(f.agencyAttention) || s(f.contactName) || ph('Contracting Officer name');
  const coEmail = s(f.contactEmail) || ph('CO email');
  const agency = s(f.agencyName) || ph('Agency');
  const agencyAddr = [f.agencyAddress?.street, [f.agencyAddress?.city, f.agencyAddress?.state, f.agencyAddress?.zip].filter(Boolean).join(', ')]
    .filter(Boolean).join('\n') || ph('Agency address');

  // --- Subject ---
  const solNo = s(f.solicitationNumber) || ph('Solicitation number');
  const projectTitle = s(f.projectTitle) || ph('Project title');
  const projectLoc = s(f.agencyAddress?.city) ? `${f.agencyAddress?.city}, ${s(f.agencyAddress?.state)}` : ph('Project location');

  // --- (a)-(d) body values ---
  const primeOrSub = 'PRIME'; // most SS responses are prime intent; user edits if sub
  const certs = (f.requiredCertifications && f.requiredCertifications.length
    ? f.requiredCertifications
    : (Array.isArray(id.certifications) ? (id.certifications as string[]) : [])
  ).filter(Boolean);
  const certPhrase = certs.length ? certs.join(', ') + ' certified' : ph('your set-aside certification') + ' certified';
  // "an 8(a)", "an SDVOSB", "a HUBZone", "a WOSB" — pick the article by how the
  // term is READ aloud. 8(a) reads "eight-A" (vowel). An all-caps initialism
  // whose first letter is spelled out (S→"ess", F→"eff") takes "an" when that
  // letter-name starts with a vowel sound (F,H,L,M,N,R,S,X). But an acronym
  // pronounced as a WORD (HUBZone="hubzone", WOSB="woz-b") follows its first
  // actual letter. Heuristic: treat as a spelled-out initialism only when it's
  // ALL caps with no lowercase (SDVOSB) — mixed case (HUBZone) reads as a word.
  const cp = certPhrase.trim();
  const isSpelledInitialism = /^[A-Z0-9()]+(?:\s|$)/.test(cp) && !/[a-z]/.test(cp.split(/\s/)[0]);
  const startsVowelSound = /^[8aeiou]/i.test(cp) || (isSpelledInitialism && /^[FHLMNRSX]/.test(cp));
  const certArticle = startsVowelSound ? 'an' : 'a';
  const location = [s(id.hq_city), s(id.hq_state)].filter(Boolean).join(', ') || ph('your city, state');
  const bondSingle = fmtMoney(id.bonding_single) || ph('$single');
  const bondAgg = fmtMoney(id.bonding_aggregate) || ph('$aggregate');

  // --- (d) differentiator: use the vault one-liner/elevator pitch if present,
  // else a labeled placeholder so the user writes their own positioning line.
  const oneLiner = s(id.one_liner) || s(id.elevator_pitch);
  const differentiator = oneLiner
    ? oneLiner
    : ph('One-sentence differentiator — e.g. "Our firm is the only 8(a) certified abatement specialist in the New England District."');

  // --- Contact person ---
  const contactName = s(id.contact_name) || ph('Your name');
  const contactTitle = s(id.contact_title) || ph('Your title');
  const contactCell = s(id.contact_phone) || ph('Cell phone');

  const letter = `${company}
DUNS: ${duns}    CAGE Code: ${cage}
${addr}
${phone}

${ph('Date')}

${coName}                                  Email: ${coEmail}
${ph('CO title')}
${agency}
${agencyAddr}

Subject:    Solicitation No. ${solNo}
            ${projectLoc}
            ${projectTitle}

Dear Mr./Ms. ${salutationName(coName)},

Thank you for allowing us this opportunity to present our firm, ${company}, as a potential suitor for the ${projectTitle} and any upcoming projects for ${agency}.

(a) ${company} intends to submit a proposal for this solicitation as a ${primeOrSub} contractor.

(b) Attached to this document you will find a copy of our bonding letter. Single/Aggregate Limits ${bondSingle} / ${bondAgg}.

(c) ${company} is ${certArticle} ${certPhrase} company based out of ${location}.

(d) Please see attached past performance and relevant experience. ${differentiator}

Responsible Office                    Contact Person
${company}                            ${contactName}
${addr}                               ${contactTitle}
${phone}                              Cell: ${contactCell}

Sincerely,


${contactName}, ${contactTitle}`;

  // One clean separation between the letter and the experience appendix.
  return `${letter}\n\n\n${relevantExperienceBlock(vault)}`;
}
