#!/usr/bin/env npx tsx
/**
 * Re-derive the REPEAT-BUYER agency×NAICS pairs for src/lib/opportunities/repeat-buyer.ts.
 *
 * A "repeat buyer" of a NAICS = an agency with >= REPEAT_BUYER_MIN (8) real awards in that NAICS,
 * counted from recompete_opportunities (quality_flag IS NULL), grouped by
 * (normalizeAgencyKey(awarding_agency), naics_code). Only qualifying pairs are emitted — the strand
 * fires ONLY on a real repeated pattern, never a one-off (no fabrication).
 *
 * Read-only. Prints the paste-able REPEAT_BUYER_PAIRS Set body (+ a coverage summary). Run when the
 * award data materially shifts (e.g. after a large recompete resync), same cadence as
 * scripts/build-sap-friendly-agencies.ts.
 *
 *   npx tsx scripts/build-repeat-buyer-map.ts
 *   npx tsx scripts/build-repeat-buyer-map.ts --write    # also splices the Set into repeat-buyer.ts
 */
import 'dotenv/config';
import { config as loadEnv } from 'dotenv';
loadEnv({ path: '.env.local' });
import { createClient } from '@supabase/supabase-js';
import { readFileSync, writeFileSync } from 'node:fs';
import { normalizeAgencyKey } from '../src/lib/gov-contacts/agency-key';
import { REPEAT_BUYER_MIN, repeatBuyerKey } from '../src/lib/opportunities/repeat-buyer';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const sb: any = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!);

async function main() {
  // Pull (awarding_agency, awarding_sub_agency, naics_code) for every real per-contract row and count
  // per (normalized-agency, naics). We count BOTH the department and the sub-agency key so a pin whose
  // agency is either taxonomy label resolves — mirrors buyer-behavior.ts's OR(agency, sub_agency).
  type Row = { awarding_agency: string | null; awarding_sub_agency: string | null; naics_code: string | null };
  const counts = new Map<string, number>();
  let scanned = 0;
  for (let from = 0; ; from += 1000) {
    const { data, error } = await sb.from('recompete_opportunities')
      .select('awarding_agency,awarding_sub_agency,naics_code')
      .is('quality_flag', null)
      .range(from, from + 999);
    if (error) { console.error('ERR recompete_opportunities:', error.message); process.exit(1); }
    if (!data || !data.length) break;
    for (const r of data as Row[]) {
      // naics_code is occasionally a non-string (a JSON object slipped in on a few rows) — coerce and
      // ACCEPT ONLY a well-formed 2–6 digit code. Anything else is dropped, never stringified to junk
      // like "[object Object]" (a real bug the unit test caught).
      const nc = String(r.naics_code ?? '').trim();
      if (!/^\d{2,6}$/.test(nc)) continue;
      // Count once per DISTINCT normalized agency key on the row (dept + sub-agency), so a row whose
      // dept and sub-agency normalize to the same key isn't double-counted.
      const keys = new Set<string>();
      for (const raw of [r.awarding_agency, r.awarding_sub_agency]) {
        const k = normalizeAgencyKey(raw || '');
        if (k) keys.add(k);
      }
      for (const k of keys) {
        const pk = repeatBuyerKey(k, nc);
        counts.set(pk, (counts.get(pk) || 0) + 1);
      }
    }
    scanned += data.length;
    if (data.length < 1000 || from > 300000) break;
  }

  const pairs = [...counts.entries()].filter(([, n]) => n >= REPEAT_BUYER_MIN).map(([pk]) => pk).sort();
  const distinctAgencies = new Set(pairs.map((p) => p.split('|')[0])).size;
  const distinctNaics = new Set(pairs.map((p) => p.split('|')[1])).size;

  console.error(`\nScanned ${scanned} award rows.`);
  console.error(`Qualifying pairs (>= ${REPEAT_BUYER_MIN} awards): ${pairs.length}  ·  ${distinctAgencies} agencies × ${distinctNaics} NAICS`);
  console.error('---- paste the Set body below into src/lib/opportunities/repeat-buyer.ts ----\n');

  const body = pairs.map((p) => `  ${JSON.stringify(p)},`).join('\n');
  const setBlock =
    `export const REPEAT_BUYER_PAIRS: ReadonlySet<string> = new Set<string>([\n` +
    `  // GENERATED by scripts/build-repeat-buyer-map.ts (${new Date().toISOString().slice(0, 10)}) — ` +
    `${pairs.length} pairs, >= ${REPEAT_BUYER_MIN} awards each. Do NOT hand-edit.\n` +
    `${body}\n]);`;
  console.log(setBlock);

  if (process.argv.includes('--write')) {
    const path = 'src/lib/opportunities/repeat-buyer.ts';
    const src = readFileSync(path, 'utf8');
    const re = /export const REPEAT_BUYER_PAIRS: ReadonlySet<string> = new Set<string>\(\[[\s\S]*?\]\);/;
    if (!re.test(src)) { console.error('Could not find REPEAT_BUYER_PAIRS block to replace.'); process.exit(1); }
    writeFileSync(path, src.replace(re, setBlock));
    console.error(`\n✓ Wrote ${pairs.length} pairs into ${path}. Run tsc + tests, then commit.`);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
