-- Recompete data-integrity fixes (issue #280)
--
-- 1. lead_time_months has always been wrong: EXTRACT(MONTH FROM AGE(...))
--    returns only the MONTHS COMPONENT of the interval (0-11) and silently
--    discards the years. A contract ending 18 months out recorded 6.
--    Verified live 2026-07-16: period_of_performance_current_end = 2028-01-16
--    (18 months away) stored lead_time_months = 6.
--    The recompete_stats view buckets expiring_6/12/18_months off this field,
--    so those buckets have been wrong for as long as the trigger has existed.
--
-- 2. The 9,388 rows with data_source='contracts-data-import' are not
--    contracts. scripts/import-existing-recompete.js loaded them from
--    public/contracts-data.js, which build-recompete-data generated by
--    GROUPING awards on Recipient+Agency+NAICS and taking the group's EARLIEST
--    end date, keeping one representative PIID. So a row's PIID and its expiry
--    date can describe different contracts, and none carry incumbent_uei.
--    They are flagged rather than deleted (reversible; query.ts already
--    filters quality_flag IS NULL, so flagging removes them from all reads).
--
-- Idempotent. Safe to re-run.

-- 1. Fix the computed-fields trigger ------------------------------------------

CREATE OR REPLACE FUNCTION update_recompete_computed_fields()
RETURNS TRIGGER AS $$
BEGIN
  NEW.estimated_recompete_date := NEW.period_of_performance_current_end - INTERVAL '12 months';

  -- Total months, not just the months component. AGE() yields e.g.
  -- "1 year 6 mons 0 days"; the old code read that as 6.
  NEW.lead_time_months := GREATEST(
    0,
    (
      EXTRACT(YEAR FROM AGE(NEW.period_of_performance_current_end, CURRENT_DATE)) * 12
      + EXTRACT(MONTH FROM AGE(NEW.period_of_performance_current_end, CURRENT_DATE))
    )::INT
  );

  NEW.recompete_likelihood := compute_recompete_likelihood(
    NEW.period_of_performance_current_end,
    NEW.options_remaining,
    NEW.total_obligation
  );

  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_recompete_computed ON recompete_opportunities;
CREATE TRIGGER trg_recompete_computed
  BEFORE INSERT OR UPDATE ON recompete_opportunities
  FOR EACH ROW EXECUTE FUNCTION update_recompete_computed_fields();

-- 2. Recompute lead_time_months for existing rows ------------------------------
-- Data-preserving: only rewrites the derived column, using the same formula as
-- the trigger above.

UPDATE recompete_opportunities
SET lead_time_months = GREATEST(
  0,
  (
    EXTRACT(YEAR FROM AGE(period_of_performance_current_end, CURRENT_DATE)) * 12
    + EXTRACT(MONTH FROM AGE(period_of_performance_current_end, CURRENT_DATE))
  )::INT
)
WHERE period_of_performance_current_end IS NOT NULL
  AND lead_time_months IS DISTINCT FROM GREATEST(
    0,
    (
      EXTRACT(YEAR FROM AGE(period_of_performance_current_end, CURRENT_DATE)) * 12
      + EXTRACT(MONTH FROM AGE(period_of_performance_current_end, CURRENT_DATE))
    )::INT
  );

-- 3. Retire the grouped/synthetic rows -----------------------------------------
-- Reversible: UPDATE ... SET quality_flag = NULL WHERE quality_flag =
-- 'grouped_synthetic' restores them. Run this ONLY once the real per-contract
-- sweep has covered the NAICS you care about, or coverage will drop.

UPDATE recompete_opportunities
SET quality_flag = 'grouped_synthetic'
WHERE data_source = 'contracts-data-import'
  AND quality_flag IS NULL;

-- Verification (expect: grouped rows flagged, real rows carry UEI)
--   SELECT data_source, quality_flag, count(*),
--          count(incumbent_uei) AS with_uei
--   FROM recompete_opportunities
--   GROUP BY 1, 2 ORDER BY 3 DESC;
