/**
 * GET /api/admin/platform-health?password=…
 *
 * The Observatory's self-measurement. See `src/lib/analytics/platform-health.ts` for the rule this
 * enforces: never report a status we did not measure — `unknown` + `blockedBy` is a first-class
 * outcome, and a check that throws surfaces as `unknown`, never as green.
 */
import { NextRequest, NextResponse } from 'next/server';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { getPlatformHealth } from '@/lib/analytics/platform-health';
import { getMeasurementIntegrity, getIntegrityStatusBlock } from '@/lib/analytics/measurement-integrity';
import { instrumentationCoverage } from '@/lib/integrity/surface-registry';

/**
 * OBSERVABLE DEBT — known truncation-risk findings.
 *
 * Eric, 2026-08-22: "the important part isn't that the gate exists. It's that you now have a
 * known debt inventory instead of an unknown correctness risk... That turns technical debt into
 * observable debt."
 *
 * Read straight from the gate's own baseline so this number CANNOT drift from what CI enforces —
 * a hand-maintained copy would be the same class of bug this whole exercise is about.
 *
 * ⚠️ Going DOWN is only good if a route became provably bounded, paginated, or exact. Eric:
 * "don't celebrate getting it to zero by suppressing findings." A drop that coincides with new
 * `truncation-ok:` waivers is not progress — it is the number lying about itself.
 */
function truncationDebt(): { known: number; measured: boolean; note: string } {
  try {
    const raw = readFileSync(join(process.cwd(), 'tests/fixtures/api-truncation-baseline.json'), 'utf8');
    const known = (JSON.parse(raw).violations || []).length;
    return {
      known,
      measured: true,
      note: 'Unpaginated reads under src/app/api whose result feeds a count, cohort, percentage or eligibility. Internal signal, not a customer metric. Down is only good when a route became bounded/paginated/exact — never when a finding was suppressed.',
    };
  } catch {
    // Never guess. An unreadable baseline is 'unknown', consistent with this route's own rule.
    return { known: -1, measured: false, note: 'baseline unreadable — not measured' };
  }
}

/**
 * Risk split of the truncation baseline (0 operational / N admin-review / M bounded).
 *
 * Reads a JSON FIXTURE, never the classifier script. A Next route cannot `require()` a file
 * outside its bundle: that version compiled locally and FAILED the Vercel build with
 * "very dynamic requires", shipping a broken production deploy. Data crosses the boundary,
 * code does not — the same reason truncationDebt() reads the gate's baseline file directly.
 *
 * The fixture is regenerated by scripts/classify-truncation-findings.mjs, so it still cannot
 * drift from the gate. Unreadable → measured:false, and the block omits the lines rather than
 * printing numbers it did not measure.
 */
function truncationRisk() {
  try {
    const raw = readFileSync(join(process.cwd(), 'tests/fixtures/truncation-risk.json'), 'utf8');
    const r = JSON.parse(raw);
    return {
      measured: r.measured === true,
      operational: Number(r.operational ?? -1),
      adminReview: Number(r.adminReview ?? -1),
      bounded: Number(r.bounded ?? -1),
      total: Number(r.total ?? -1),
    };
  } catch {
    return { measured: false, operational: -1, adminReview: -1, bounded: -1, total: -1 };
  }
}

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;

const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '';

export async function GET(request: NextRequest) {
  const pw = request.nextUrl.searchParams.get('password');
  if (!ADMIN_PASSWORD || pw !== ADMIN_PASSWORD) {
    return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });
  }
  try {
    const health = await getPlatformHealth();
    return NextResponse.json({
      ok: true,
      ...health,
      truncationDebt: truncationDebt(),
      // The at-a-glance status block. Fed the gate's own finding count so the two can
      // never disagree; -1 (baseline unreadable) surfaces as 'unknown', not a guess.
      decisionMetricsIntegrity: getIntegrityStatusBlock(truncationDebt().known, truncationRisk()),
      // INSTRUMENTATION COVERAGE — read this BEFORE interpreting any usage figure. A surface
      // we cannot observe reports 0, and that 0 must never be read as "nobody uses it".
      // Derived from the Product Surface Registry; `audit-instrumentation.mjs` re-checks the
      // registry against live engagement data and fails on drift.
      instrumentationCoverage: instrumentationCoverage(),
      // THE NUMBER THAT MATTERS BEFORE A PRODUCT CALL (Eric, 2026-08-22): "131 -> 129 tells
      // you code debt is shrinking. But 1/30 verified tells you how much of the product's
      // decision-making instrumentation you can currently trust." Kept SEPARATE from the
      // operational risks so the trust problem is not overstated.
      measurementIntegrity: getMeasurementIntegrity(),
      note:
        'Platform Health measures the measurement system. A status is only reported when it was ' +
        'actually checked; anything we could not verify appears under `unmeasured` with its blocker ' +
        'rather than being guessed at.',
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ ok: false, error: msg }, { status: 500 });
  }
}
