/**
 * Maps AGENCIES_SEO slugs to the canonical `awarding_agency` string
 * stored in BigQuery (`market-assasin.usaspending.agency_summary`).
 *
 * Why a separate file: `agencies-seo.ts` is auto-generated by
 * `scripts/build-agencies-seo.py` and gets clobbered on regeneration.
 * Keeping the BQ mapping here means it survives data refreshes.
 *
 * Rules:
 *  - If the slug's title-case form already matches BQ exactly, we don't
 *    need an entry — `getBqAgencyName()` derives it from the slug.
 *  - If BQ uses a different name (rebranded agencies, abbreviations),
 *    add an explicit override.
 *  - If the agency has NO presence in BQ at all (sub-bureaus rolled
 *    into a parent, off-budget agencies), set the value to `null` and
 *    the Federal Award Activity section will be omitted gracefully.
 *
 * Source of truth for BQ names:
 *   SELECT DISTINCT awarding_agency
 *   FROM `market-assasin.usaspending.agency_summary`
 *   ORDER BY awarding_agency
 */

// Explicit overrides only — most agencies match by slug-to-title-case.
// `null` means "no BQ counterpart, skip the section entirely".
const BQ_AGENCY_OVERRIDES: Record<string, string | null> = {
  // Rebranded 2018: Broadcasting Board of Governors → U.S. Agency for Global Media
  'broadcasting-board-of-governors': 'U.S. Agency for Global Media',
  // BQ drops the "U.S." prefix
  'us-international-trade-commission': 'International Trade Commission',
  // No standalone presence in BQ — rolled up under Department of Defense
  'corps-of-engineers-civil-works': null,
  // Off-budget, no contracts in USASpending
  'tennessee-valley-authority': null,
  // Self-funded via deposit insurance, doesn't appear in BQ
  'federal-deposit-insurance-corporation': null,
  // Tiny binational agency, not in BQ awards data
  'international-boundary-and-water-commission': null,
};

/**
 * Resolve the BQ `awarding_agency` string for an agency slug.
 * Returns `null` if the agency has no presence in BQ.
 */
export function getBqAgencyName(slug: string, agencyName: string): string | null {
  if (slug in BQ_AGENCY_OVERRIDES) {
    return BQ_AGENCY_OVERRIDES[slug];
  }
  // Default: the static `name` field is already title-case and matches
  // BQ's `awarding_agency` exactly for ~85% of our 49 agencies.
  return agencyName;
}
